micronaut:
  application:
    name: LastkatkaBot
  server:
    port: 1457
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
  executors:
    scheduled:
      type: scheduled
      core-pool-size: 3

endpoints:
  prometheus:
    sensitive: false

# you can also use unix domain socket connection:

# mongodb:
#  uri: mongodb://user:password@%2Ftmp%2Fmongodb-27017.sock/database?directConnection=true&authSource=admin

mongodb:
  uri: "mongodb://user:password@host:port/database?directConnection=true&authSource=admin"

jackson:
  serializationInclusion: ALWAYS

bot:
  username: ${BOT_USERNAME} # bot username without @
  token: ${BOT_TOKEN} # telegram bot token

  timezone: "Europe/Kiev" # timezone for /pair, /wish and other time-based features

  mainAdminId: ${main-admin-id} # id of main admin
  notificationChannelId: ${notification-channel-id} # id of channel/group where feedbacks and error logs will be sent
